# Generated by Django 4.0.6 on 2022-08-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tumans',
                'ordering': ('region_id',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'regions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tugarak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('narxi', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('qabul', models.IntegerField(default=2)),
                ('regio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.district')),
            ],
            options={
                'db_table': 'tugaraks',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.region'),
        ),
    ]
