# Generated by Django 4.0.6 on 2022-08-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_tugarak_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('region',)},
        ),
        migrations.RenameField(
            model_name='district',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='tugarak',
            old_name='regio_id',
            new_name='regio',
        ),
    ]
