# Generated by Django 4.0.6 on 2022-08-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugarak',
            name='phone_number',
            field=models.CharField(default=1, max_length=255, verbose_name='Aloqa nomeri'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.region', verbose_name='Viloyat nomi'),
        ),
        migrations.AlterField(
            model_name='tugarak',
            name='name',
            field=models.CharField(max_length=255, verbose_name="To'garak nomi"),
        ),
        migrations.AlterField(
            model_name='tugarak',
            name='regio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.district', verbose_name='Tuman nomi'),
        ),
    ]
