# Generated by Django 4.0.6 on 2022-08-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_tugarak_phone_number_alter_district_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tugarak',
            name='narxi',
        ),
        migrations.RemoveField(
            model_name='tugarak',
            name='qabul',
        ),
    ]
