# Generated by Django 4.0.6 on 2022-08-15 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_tugarak_narxi_remove_tugarak_qabul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tugarak',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tugarak',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='Cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='yunalish nomi')),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=255, verbose_name='Aloqa nomeri')),
                ('regio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.district', verbose_name='Cources name')),
            ],
            options={
                'db_table': 'Cources',
            },
        ),
    ]
