# Generated by Django 4.0.6 on 2022-08-17 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_tugarak_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yunalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="yo'nalish nomi")),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=255, verbose_name='Aloqa nomeri')),
                ('regio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.district', verbose_name="To'garak nomi")),
            ],
            options={
                'db_table': 'yunalish',
            },
        ),
        migrations.DeleteModel(
            name='Cources',
        ),
    ]
