# Generated by Django 4.0.6 on 2022-08-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_yunalish_delete_cources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yunalish',
            name='regio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.tugarak', verbose_name="To'garak nomi"),
        ),
    ]
